;;; do-at-point-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from do-at-point.el

(autoload 'do-at-point "do-at-point" "\
Focus on a THING at point.
If invoked interactively with a prefix argument or with the
optional argument THING, one can set the initial thing to be
selected.

(fn &optional THING)" t)
 (put 'do-at-point 'setup-func 'do-at-point)
(register-definition-prefixes "do-at-point" '("do-at-point-"))


;;; End of scraped data

(provide 'do-at-point-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; do-at-point-autoloads.el ends here
