;;; har-viewer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from har-viewer.el

(autoload 'har-viewer-mode "har-viewer" "\
Major mode for viewing HTTP Archive (HAR) files.

(fn)" t)
(autoload 'har-viewer-view "har-viewer" "\
Open a HAR viewer for the current buffer." t)
(autoload 'har-viewer-minor-mode "har-viewer" "\
Minor mode that provides \\[har-viewer-view] in .har file buffers.

This is a minor mode.  If called interactively, toggle the `Har-Viewer
minor mode' mode.  If the prefix argument is positive, enable the mode,
and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `har-viewer-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'har-viewer-global-minor-mode 'globalized-minor-mode t)
(defvar har-viewer-global-minor-mode nil "\
Non-nil if Har-Viewer-Global minor mode is enabled.
See the `har-viewer-global-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `har-viewer-global-minor-mode'.")
(custom-autoload 'har-viewer-global-minor-mode "har-viewer" nil)
(autoload 'har-viewer-global-minor-mode "har-viewer" "\
Toggle Har-Viewer minor mode in all buffers.
With prefix ARG, enable Har-Viewer-Global minor mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Har-Viewer minor mode is enabled in all buffers where
`har-viewer-minor-mode--maybe-enable' would do it.

See `har-viewer-minor-mode' for more information on Har-Viewer minor mode.

(fn &optional ARG)" t)
(register-definition-prefixes "har-viewer" '("har-viewer-"))

;;; End of scraped data

(provide 'har-viewer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; har-viewer-autoloads.el ends here
