;;; qrencode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from qrencode.el

(autoload 'qrencode-region "qrencode" "\
Encode region between BEG and END into a QR code and show in a buffer.

(fn BEG END)" t)
(autoload 'qrencode-url-at-point "qrencode" "\
Encode any URL found at point." t)
(autoload 'qrencode-string "qrencode" "\
Encode STR.
When called interactively, read STR with `read-string'.

(fn STR)" t)
(register-definition-prefixes "qrencode" '("qrencode"))

;;; End of scraped data

(provide 'qrencode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; qrencode-autoloads.el ends here
