;;; aggressive-fill-paragraph-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from aggressive-fill-paragraph.el

(autoload 'aggressive-fill-paragraph-mode "aggressive-fill-paragraph" "\
Toggle automatic paragraph fill when spaces are inserted in comments.

This is a minor mode.  If called interactively, toggle the
`Aggressive-Fill-Paragraph mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `aggressive-fill-paragraph-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'afp-setup-recommended-hooks "aggressive-fill-paragraph" "\
Install hooks to enable function ‘aggressive-fill-paragraph-mode’
in recommended major modes." t)
(register-definition-prefixes "aggressive-fill-paragraph" '("afp-" "aggressive-fill-paragraph-post-self-insert-function"))

;;; End of scraped data

(provide 'aggressive-fill-paragraph-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; aggressive-fill-paragraph-autoloads.el ends here
