;;; evil-magit-autoloads.el --- automatically extracted autoloads
;;
;;; Code:
(add-to-list 'load-path (or (file-name-directory #$) (car load-path)))

;;;### (autoloads nil "evil-magit" "evil-magit.el" (22084 31810 0
;;;;;;  0))
;;; Generated autoloads from evil-magit.el

(autoload 'evil-magit-revert-section-bindings "evil-magit" "\
Revert changed bindings in section maps generated by evil-magit

\(fn)" t nil)

(autoload 'evil-magit-revert "evil-magit" "\
Revert changes by evil-magit that affect default evil+magit behavior.

\(fn)" t nil)

;;;***

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; End:
;;; evil-magit-autoloads.el ends here
