;;; tree-sitter-ispell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tree-sitter-ispell.el

(autoload 'tree-sitter-ispell-run-at-point "tree-sitter-ispell" "\
Run ispell at current point if there is a text node." t)
(autoload 'tree-sitter-ispell-run-buffer "tree-sitter-ispell" "\
Run ispell for every text node for the current buffer." t)
(register-definition-prefixes "tree-sitter-ispell" '("tree-sitter-ispell-"))

;;; End of scraped data

(provide 'tree-sitter-ispell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tree-sitter-ispell-autoloads.el ends here
