;;; pyimpsort-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pyimpsort.el

(autoload 'pyimpsort-region "pyimpsort" "\
Sort python imports from region BEGIN to END points.

(fn BEGIN END)" t)
(autoload 'pyimpsort-buffer "pyimpsort" "\
Sort python imports from current buffer." t)
(register-definition-prefixes "pyimpsort" '("pyimpsort-"))

;;; End of scraped data

(provide 'pyimpsort-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pyimpsort-autoloads.el ends here
