;;; know-your-http-well-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from http-headers.el

(autoload 'http-header "http-headers" "\
Display the meaning of an HTTP header

(fn HEADER)" t)
(register-definition-prefixes "http-headers" '("http-headers"))


;;; Generated autoloads from http-methods.el

(autoload 'http-method "http-methods" "\
Display the meaning of an HTTP method

(fn METHOD)" t)
(register-definition-prefixes "http-methods" '("http-methods"))


;;; Generated autoloads from http-relations.el

(autoload 'http-relation "http-relations" "\
Display the meaning of an HTTP relation

(fn RELATION)" t)
(register-definition-prefixes "http-relations" '("http-relations"))


;;; Generated autoloads from http-status-codes.el

(autoload 'http-status-code "http-status-codes" "\
Display the meaning of an HTTP status code or phrase

(fn STATUS)" t)
(register-definition-prefixes "http-status-codes" '("http-status"))


;;; Generated autoloads from media-types.el

(autoload 'media-type "media-types" "\
Display the template of a media-type

(fn MEDIA-TYPE)" t)
(register-definition-prefixes "media-types" '("media-types"))

;;; End of scraped data

(provide 'know-your-http-well-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; know-your-http-well-autoloads.el ends here
