;;; nodejs-repl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nodejs-repl.el

(autoload 'nodejs-repl-send-line "nodejs-repl" "\
Send the current line to the `nodejs-repl-process'." t)
(autoload 'nodejs-repl-send-region "nodejs-repl" "\
Send the current region from START to END to the `nodejs-repl-process'.

(fn START END)" t)
(autoload 'nodejs-repl-send-buffer "nodejs-repl" "\
Send the current buffer to the `nodejs-repl-process'." t)
(autoload 'nodejs-repl-load-file "nodejs-repl" "\
Load the FILE to the `nodejs-repl-process'.

(fn FILE)" t)
(autoload 'nodejs-repl-send-last-expression "nodejs-repl" "\
Send the expression before point to the `nodejs-repl-process'." t)
(autoload 'nodejs-repl-switch-to-repl "nodejs-repl" "\
Switch to a `nodejs-repl-process', spawning a new one if necessary." t)
(autoload 'nodejs-repl "nodejs-repl" "\
Run Node.js REPL." t)
(autoload 'nodejs-repl-minor-mode "nodejs-repl" "\
A minor mode for Node.js REPL

This is a minor mode.  If called interactively, toggle the
`Nodejs-Repl minor mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `nodejs-repl-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "nodejs-repl" '("nodejs-repl-"))

;;; End of scraped data

(provide 'nodejs-repl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nodejs-repl-autoloads.el ends here
