;;; php-runtime-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from php-runtime.el

(eieio-defclass-autoload 'php-runtime-execute 'nil "\
php-runtime" nil)
(autoload 'php-runtime-expr "php-runtime" "\
Evaluate and echo PHP expression PHP-EXPR.

Pass INPUT-BUFFER to PHP executable as STDIN.

(fn PHP-EXPR &optional INPUT-BUFFER)")
(autoload 'php-runtime-eval "php-runtime" "\
Evaluate PHP code CODE without open tag, and return buffer.

Pass INPUT-BUFFER to PHP executable as STDIN.
Pass OUTPUT-BUFFER to PHP executable as STDOUT.

(fn CODE &optional INPUT-BUFFER OUTPUT-BUFFER)")
(autoload 'php-runtime-extension-loaded-p "php-runtime" "\
Return T if EXTENSION is loaded.

(fn EXTENSION)")
(register-definition-prefixes "php-runtime" '("php-runtime-"))

;;; End of scraped data

(provide 'php-runtime-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; php-runtime-autoloads.el ends here
