;;; accent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from accent.el

(autoload 'accent-menu "accent" "\
Display a popup completion menu with accents, if current character is matching." t)
(autoload 'accent-company "accent" "\
Use `company' to display a completion menu for accented characters at point.

See `company-backends' for the description of COMMAND.

(fn COMMAND &rest IGNORED)" t)
(autoload 'accent-corfu "accent" "\
Use `corfu' to display a completion menu for accented characters at point." t)
(register-definition-prefixes "accent" '("accent-"))

;;; End of scraped data

(provide 'accent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; accent-autoloads.el ends here
