;;; bicycle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bicycle.el

(autoload 'bicycle-cycle "bicycle" "\
Cycle local or global visibility.

With a prefix argument call `bicycle-cycle-global'.
Without a prefix argument call `bicycle-cycle-local'.

(fn &optional GLOBAL)" t)
(autoload 'bicycle-cycle-global "bicycle" "\
Cycle visibility of all sections.

1. OVERVIEW: Show only top-level headings.

(2.          There is no equivalent of `bicycle-cycle-local's
             CHILDREN state.)

3. TOC:      Recursively show all headings,
             without treating code blocks as sections.

4. TREES:    Recursively show all headings,
             treating code blocks as sections
             (i.e., their first line is treated as a heading).

5. ALL:      Show everything, including code blocks,
             empty lines and comments.
             However, do not expand code blocks that were
             previously collapsed individually.

In situations when cycling to a state makes no difference compared
to the previous state, then immediately continue to the next state." t)
(register-definition-prefixes "bicycle" '("bicycle-" "outline-code-level"))

;;; End of scraped data

(provide 'bicycle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bicycle-autoloads.el ends here
