;;; bnf-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bnf-mode.el

(let ((loads (get 'bnf 'custom-loads))) (if (member '"bnf-mode" loads) nil (put 'bnf 'custom-loads (cons '"bnf-mode" loads)) (put 'languages 'custom-loads (cons 'bnf (get 'languages 'custom-loads)))))
(autoload 'bnf-mode "bnf-mode" "\
A major mode for editing BNF grammars.

\\{bnf-mode-map}

Turning on BNF Mode calls the value of `prog-mode-hook' and then of
`bnf-mode-hook', if they are non-nil.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.bnf\\'" . bnf-mode))
(register-definition-prefixes "bnf-mode" '("bnf-"))

;;; End of scraped data

(provide 'bnf-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bnf-mode-autoloads.el ends here
