;;; browse-kill-ring-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from browse-kill-ring.el

(autoload 'browse-kill-ring-default-keybindings "browse-kill-ring" "\
Make `yank-pop' invoke `browse-kill-ring' when appropriate.
Normally, `yank-pop' is only useful after `yank'.  This installs
advice so that invoking `yank-pop' otherwise runs `browse-kill-ring'
instead." t)
(autoload 'browse-kill-ring "browse-kill-ring" "\
Display items in the `kill-ring' in another buffer." t)
(register-definition-prefixes "browse-kill-ring" '("browse-kill-ring-"))

;;; End of scraped data

(provide 'browse-kill-ring-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; browse-kill-ring-autoloads.el ends here
