;;; khalel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from khalel.el

(register-definition-prefixes "khalel" '("khalel-"))


;;; Generated autoloads from khalel-icalendar.el

(register-definition-prefixes "khalel-icalendar" '("khalel-icalendar--"))

;;; End of scraped data

(provide 'khalel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; khalel-autoloads.el ends here
