;;; graphql-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from graphql-mode.el

(autoload 'graphql-mode "graphql-mode" "\
A major mode to edit GraphQL schemas.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.graphql\\'" . graphql-mode))
(add-to-list 'auto-mode-alist '("\\.gql\\'" . graphql-mode))
(register-definition-prefixes "graphql-mode" '("graphql-"))

;;; End of scraped data

(provide 'graphql-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; graphql-mode-autoloads.el ends here
