;;; glsl-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from glsl-db.el

(register-definition-prefixes "glsl-db" '("glsl-"))


;;; Generated autoloads from glsl-mode.el

(add-to-list 'auto-mode-alist '("\\.vert\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.frag\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.geom\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.tesc\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.tese\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.mesh\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.task\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.comp\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rgen\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rint\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rchit\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rahit\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rcall\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.rmiss\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.glsl\\'" . glsl-mode))
(autoload 'glsl-mode "glsl-mode" "\
Major mode for editing GLSL shader files.

\\{glsl-mode-map}

(fn)" t)
(register-definition-prefixes "glsl-mode" '("glsl-"))


;;; Generated autoloads from glsl-ts-mode.el

(autoload 'glsl-ts-mode "glsl-ts-mode" "\
Major mode for editing GLSL shaders with tree-sitter.

\\{glsl-ts-mode-map}

(fn)" t)
(register-definition-prefixes "glsl-ts-mode" '("glsl-ts-"))

;;; End of scraped data

(provide 'glsl-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; glsl-mode-autoloads.el ends here
