;;; term-manager-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from term-manager.el

(register-definition-prefixes "term-manager" '("term-manager"))


;;; Generated autoloads from term-manager-eat.el

(register-definition-prefixes "term-manager-eat" '("term-manager-eat-build-term"))


;;; Generated autoloads from term-manager-indexed-mapping.el

(register-definition-prefixes "term-manager-indexed-mapping" '("term-manager-"))

;;; End of scraped data

(provide 'term-manager-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; term-manager-autoloads.el ends here
