;;; speed-type-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from speed-type.el

(autoload 'speed-type-text-top-x "speed-type" "\
Calculate a frequency list of a random gutenberg book.

Then assembles the text from the X most common words. Starting a
speed-type session with the assembled text.

The frequency list is stored at `speed-type-directory' ([book-num]-top-x.txt).

If `speed-type-default-lang' is set, will pick a random book of that language.

(fn X)" t)
(autoload 'speed-type-top-x "speed-type" "\
Speed type the X most common words.

The frequency list is stored at `speed-type-directory' ([lang].txt).

(fn X)" t)
(autoload 'speed-type-top-100 "speed-type" "\
Speed type the top 100 most common words.

More details see `speed-type-top-x'." t)
(autoload 'speed-type-top-1000 "speed-type" "\
Speed type the top 1000 most common words.

More details see `speed-type-top-x'." t)
(autoload 'speed-type-region "speed-type" "\
Open copy of [START,END] in a new buffer to speed type the text.

(fn START END)" t)
(autoload 'speed-type-buffer-top-x "speed-type" "\
Calculate a frequency list of `current-buffer'.

Then assembles the text from the X most common words. Starting a
speed-type session with the assembled text.

(fn X)" t)
(autoload 'speed-type-buffer "speed-type" "\
Open copy of buffer contents in a new buffer to speed type the text.

If using a prefix while calling this function `C-u', then the FULL text
will be used.  Else some text will be picked randomly.

(fn FULL)" t)
(autoload 'speed-type-text "speed-type" "\
Setup a new text sample to practice touch or speed typing." t)
(autoload 'speed-type-quotes "speed-type" "\
Setup a new quote to practice touch or speed typing.

If ARG is given will prompt for a specific quote-URL.

(fn &optional ARG)" t)
(autoload 'speed-type-continue "speed-type" "\
Will continue where user left of in given FILE-NAME.

GO-NEXT-FN is supplied to the setup-functions, to provide the
next-action (random) in the complete-menu.

Find last speed-type--continue-at-point of FILE-NAME and setup a speed-type
session continuing at that last found position. If nothing is found,
will begin at `point-min' or [GUTENBERG-START].

If an `universal-argument' (4) is used, will prompt user for FILE-NAME.

If FILE-NAME is given, will continue with that given file-name.

If FILE-NAME is not found, will throw a user-error.

If FILE-NAME is nil, will use file-name of CURRENT-BUFFER.

(fn GO-NEXT-FN &optional FILE-NAME)" t)
(autoload 'speed-type-pandoc "speed-type" "\
Use pandoc to start a speed-type session.

URL is retrieved and the content are stored in `speed-type-directory'.

If the URL is already retrieved will reuse the stored content in
`speed-type-directory'.

The file-name of the content is a converted form of URL.

(fn URL)" t)
(autoload 'speed-type-pandoc-top-x "speed-type" "\
Calculate a frequency list using pandoc.

Then assembles the text from the X most common words. Starting a
speed-type session with the assembled text.

If the URL is already retrieved will reuse the stored content in
`speed-type-directory'.

The URL is converted to a unique file-name.

If the frequency list is already calculated for this URL will reuse the
stored content in `speed-type-directory'.

(fn URL &optional X)" t)
(register-definition-prefixes "speed-type" '("speed-type-"))

;;; End of scraped data

(provide 'speed-type-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; speed-type-autoloads.el ends here
