;;; eslint-disable-rule-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eslint-disable-rule.el

(autoload 'eslint-disable-rule-disable-next-line "eslint-disable-rule" "\
Add eslint-disable-next-line comment above current line to disable RULE-NAME.

If DESCRIPTION is non-nil, insert a description explaining why RULE-NAME
was disabled.

Interactively, ask for RULE-NAME by executing hooks in
`eslint-disable-rule-find-rules-hook'.  Also ask for DESCRIPTION depending
on `eslint-disable-rule-require-description'.

(fn RULE-NAME &optional DESCRIPTION)" t)
(register-definition-prefixes "eslint-disable-rule" '("eslint-disable-rule-"))


;;; Generated autoloads from eslint-disable-rule-all.el

(autoload 'eslint-disable-rule-all "eslint-disable-rule-all" "\
Return a list of all eslint rules.")
(register-definition-prefixes "eslint-disable-rule-all" '("eslint-disable-rule-all-executable"))


;;; Generated autoloads from eslint-disable-rule-flycheck.el

(autoload 'eslint-disable-rule-flycheck "eslint-disable-rule-flycheck" "\
Return a list of eslint rule names from flycheck-eslint errors.

Return nil if `flycheck' or `flycheck-eslint' are not active so it is safe,
but useless, to use even when not using flycheck.")
(register-definition-prefixes "eslint-disable-rule-flycheck" '("eslint-disable-rule-flycheck--eslint-"))


;;; Generated autoloads from eslint-disable-rule-flymake.el

(autoload 'eslint-disable-rule-flymake "eslint-disable-rule-flymake" "\
Return a list of eslint rule names from flymake-eslint errors.

Return nil if `flymake' or `flymake-eslint' are not active so it is safe,
but useless, to use even when not using flymake.")
(register-definition-prefixes "eslint-disable-rule-flymake" '("eslint-disable-rule-flymake--"))

;;; End of scraped data

(provide 'eslint-disable-rule-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eslint-disable-rule-autoloads.el ends here
