;;; tzc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tzc.el

(autoload 'tzc-convert-time "tzc" "\
Convert a given time as given in TIME-STRING from FROM-ZONE to TO-ZONE.
Optionally on a given FROM-DATE.

(fn TIME-STRING FROM-ZONE TO-ZONE FROM-DATE)" t)
(autoload 'tzc-convert-current-time "tzc" "\
Convert current local time to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-convert-time-to-favourite-time-zones "tzc" "\
Convert time in TIME-STRING from FROM-ZONE to `(tzc--favourite-time-zones)`.
The conversion is computed for the given FROM-DATE.

(fn TIME-STRING FROM-ZONE FROM-DATE)" t)
(autoload 'tzc-convert-current-time-to-favourite-time-zones "tzc" "\
Convert current local time to `(tzc--favourite-time-zones)`." t)
(autoload 'tzc-convert-time-at-mark "tzc" "\
Convert time at the marked region to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-world-clock-previous-or-next "tzc" "\
Get the `tzc-world-clock' buffer for PREVIOUS-OR-NEXT hour.

(fn PREVIOUS-OR-NEXT)")
(autoload 'tzc-world-clock-previous "tzc" "\
Get the `tzc-world-clock` for the previous hour." t)
(autoload 'tzc-world-clock-next "tzc" "\
Get the `tzc-world-clock` for the next hour." t)
(defvar tzc-world-clock-mode-map (let ((map (make-sparse-keymap))) (define-key map "n" #'tzc-world-clock-next) (define-key map "p" #'tzc-world-clock-previous) map))
(autoload 'tzc-world-clock "tzc" "\
Display a world clock buffer for time zones in `tzc-favourite-time-zones-alist`." t)
(autoload 'tzc-check-time-zone "tzc" "\
Check info for TIME-ZONE.

(fn TIME-ZONE)" t)
(autoload 'tzc-convert-org-time-stamp-at-mark "tzc" "\
Convert `org-time-stamp` at the marked region to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-convert-and-replace-org-time-stamp-at-mark "tzc" "\
Convert `org-time-stamp` at the marked region to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-get-time-shift-between-zones "tzc" "\
Get time shift between FROM-ZONE and TO-ZONE.
Optionally on a given FROM-DATE.

(fn FROM-ZONE TO-ZONE FROM-DATE)" t)
(register-definition-prefixes "tzc" '("tzc-"))

;;; End of scraped data

(provide 'tzc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tzc-autoloads.el ends here
