;;; pulsar-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pulsar.el

(autoload 'pulsar-pulse-line "pulsar" "\
Create a pulse highlight for the current line.
Also see `pulsar-highlight-pulse'." t)
(autoload 'pulsar-highlight-pulse "pulsar" "\
Highlight the current LOCUS by pulsing it.
To pulse is to add a colour and then gradually fade it away.  The pulse
is subject to `pulsar-delay' and `pulsar-iterations'.

When the region is active, LOCUS covers the region boundaries.
Otherwise, LOCUS spans the current line.

For highlights without a pulse, see `pulsar-highlight-temporarily' and
`pulsar-highlight-permanently'.

(fn &optional LOCUS)" t)
(autoload 'pulsar-highlight-temporarily "pulsar" "\
Temporarily highlight the current LOCUS.
Unlike `pulsar-highlight-pulse', never pulse the current line.  Keep the
highlight in place until another command is invoked.  This is what makes
the highlight temporary.

For a permanent highlight, see `pulsar-highlight-permanently'.

(fn LOCUS)" t)
(autoload 'pulsar-highlight-permanently "pulsar" "\
Set a permanent highlight to the current LOCUS.
When the region is active, LOCUS is a cons cell of positions
corresponding to the region boundaries.  Otherwise it is a cons cell of
positions corresponding to the beginning and end of the current line.

Remove the highlight with `pulsar-highlight-permanently-remove' or
toggle it with `pulsar-highlight-permanently'.

For a temporary highlight use `pulsar-highlight-temporarily' and
related.

(fn LOCUS)" t)
(autoload 'pulsar-highlight-permanently-dwim "pulsar" "\
Do-What-I-Mean with a permanent highlighting of the current LOCUS.
When there is a highlight, remove it, else add it.

If the region is active, LOCUS corresponds to its boundaries.  If there
is no region, then LOCUS corresponds to the boundaries of the current
line.

(fn LOCUS)" t)
(autoload 'pulsar-define-pulse-with-face "pulsar" "\
Produce function to pulse the current line with FACE.
If FACE starts with the `pulsar-' prefix, remove it and keep only
the remaining text.  The assumption is that something like
`pulsar-red' will be convered to `red', thus deriving a function
named `pulsar-pulse-line-red'.  Any other FACE is taken as-is.

(fn FACE)" nil t)
(function-put 'pulsar-define-pulse-with-face 'lisp-indent-function 'function)
(put 'pulsar-global-mode 'globalized-minor-mode t)
(defvar pulsar-global-mode nil "\
Non-nil if Pulsar-Global mode is enabled.
See the `pulsar-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `pulsar-global-mode'.")
(custom-autoload 'pulsar-global-mode "pulsar" nil)
(autoload 'pulsar-global-mode "pulsar" "\
Toggle Pulsar mode in all buffers.
With prefix ARG, enable Pulsar-Global mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Pulsar mode is enabled in all buffers where `pulsar--on' would do it.

See `pulsar-mode' for more information on Pulsar mode.

(fn &optional ARG)" t)
(register-definition-prefixes "pulsar" '("pulsar-"))

;;; End of scraped data

(provide 'pulsar-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pulsar-autoloads.el ends here
