;;; phpstan-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from phpstan.el

(defvar phpstan-working-dir nil "\
Path to working directory of PHPStan.

*NOTICE*: This is different from the project root.

STRING
     Absolute path to `phpstan' working directory.

`(root . STRING)'
     Relative path to `phpstan' working directory from project root directory.

NIL
     Use (php-project-get-root-dir) as working directory.")
(make-variable-buffer-local 'phpstan-working-dir)
(put 'phpstan-working-dir 'safe-local-variable #'(lambda (v) (if (consp v) (and (eq 'root (car v)) (stringp (cdr v))) (null v) (stringp v))))
(defvar phpstan-config-file nil "\
Path to project specific configuration file of PHPStan.

STRING
     Absolute path to `phpstan' configuration file.

`(root . STRING)'
     Relative path to `phpstan' configuration file from project root directory.

NIL
     Search phpstan.neon(.dist) in (phpstan-get-working-dir).")
(make-variable-buffer-local 'phpstan-config-file)
(put 'phpstan-config-file 'safe-local-variable #'(lambda (v) (if (consp v) (and (eq 'root (car v)) (stringp (cdr v))) (null v) (stringp v))))
(defvar-local phpstan-autoload-file nil "\
Path to autoload file for PHPStan.

STRING
     Path to `phpstan' autoload file.

`(root . STRING)'
     Relative path to `phpstan' configuration file from project root directory.

NIL
     If `phpstan-enable-on-no-config-file', search \"vendor/autoload.php\"
     in (phpstan-get-working-dir).")
(put 'phpstan-autoload-file 'safe-local-variable #'(lambda (v) (if (consp v) (and (eq 'root (car v)) (stringp (cdr v))) (null v) (stringp v))))
(defvar-local phpstan-level nil "\
Rule level of PHPStan.

INTEGER or STRING
     Number of PHPStan rule level.

max
     The highest of PHPStan rule level.

NIL
     Use rule level specified in `phpstan' configuration file.")
(put 'phpstan-level 'safe-local-variable #'(lambda (v) (or (null v) (integerp v) (eq 'max v) (and (stringp v) (string= "max" v) (string-match-p "\\`[0-9]\\'" v)))))
(defvar phpstan-replace-path-prefix)
(make-variable-buffer-local 'phpstan-replace-path-prefix)
(put 'phpstan-replace-path-prefix 'safe-local-variable #'(lambda (v) (or (null v) (stringp v))))
(defvar phpstan-executable nil "\
PHPStan excutable file.

STRING
     Absolute path to `phpstan' executable file.

`docker'
     Use Docker using phpstan/docker-image.

`(root . STRING)'
     Relative path to `phpstan' executable file.

`(STRING . (ARGUMENTS ...))'
     Command name and arguments.

NIL
     Auto detect `phpstan' executable file.")
(make-variable-buffer-local 'phpstan-executable)
(put 'phpstan-executable 'safe-local-variable #'(lambda (v) (if (consp v) (or (and (eq 'root (car v)) (stringp (cdr v))) (and (stringp (car v)) (listp (cdr v)))) (or (eq 'docker v) (null v) (stringp v)))))
(autoload 'phpstan-analyze-this-file "phpstan" "\
Analyze current buffer-file using PHPStan." t)
(autoload 'phpstan-analyze-file "phpstan" "\
Analyze a PHP script FILE using PHPStan.

(fn FILE)" t)
(autoload 'phpstan-analyze-project "phpstan" "\
Analyze a PHP project using PHPStan." t)
(autoload 'phpstan-generate-baseline "phpstan" "\
Generate PHPStan baseline file." t)
(autoload 'phpstan-find-baseline-file "phpstan" "\
Find PHPStan baseline file of current project." t)
(autoload 'phpstan-pro "phpstan" "\
Analyze current PHP project using PHPStan Pro." t)
(autoload 'phpstan-insert-ignore "phpstan" "\
Insert an @phpstan-ignore comment at the specified POSITION.

POSITION determines where to insert the comment and can be either `this-line' or
`previous-line'.

- If POSITION is `this-line', the comment is inserted at the end of
  the current line.
- If POSITION is `previous-line', the comment is inserted on a new line above
  the current line.

(fn POSITION)" t)
(autoload 'phpstan-insert-dumptype "phpstan" "\
Insert PHPStan\\dumpType() expression-statement by EXPRESSION and PREFIX-NUM.

(fn &optional EXPRESSION PREFIX-NUM)" t)
(register-definition-prefixes "phpstan" '("phpstan-"))

;;; End of scraped data

(provide 'phpstan-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; phpstan-autoloads.el ends here
