;;; activity-watch-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from activity-watch-mode.el

(autoload 'activity-watch-refresh-project-name "activity-watch-mode" "\
Recompute the name of the project for the current file." t)
(autoload 'activity-watch-mode "activity-watch-mode" "\
Toggle Activity-Watch (Activity-Watch mode).

This is a minor mode.  If called interactively, toggle the
`activity-watch mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `activity-watch-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-activity-watch-mode 'globalized-minor-mode t)
(defvar global-activity-watch-mode nil "\
Non-nil if Global Activity-Watch mode is enabled.
See the `global-activity-watch-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-activity-watch-mode'.")
(custom-autoload 'global-activity-watch-mode "activity-watch-mode" nil)
(autoload 'global-activity-watch-mode "activity-watch-mode" "\
Toggle Activity-Watch mode in all buffers.
With prefix ARG, enable Global Activity-Watch mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Activity-Watch mode is enabled in all buffers where `(lambda nil
(activity-watch-mode 1))' would do it.

See `activity-watch-mode' for more information on Activity-Watch mode.

(fn &optional ARG)" t)
(register-definition-prefixes "activity-watch-mode" '("activity-watch-"))

;;; End of scraped data

(provide 'activity-watch-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; activity-watch-mode-autoloads.el ends here
