;;; python-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from python-mode.el

(autoload 'python-mode "python-mode" "\
Major mode for editing Python files.

To submit a report, enter ‘\\[py-submit-bug-report]’
from a‘python-mode’ buffer.
Do ‘\\[py-describe-mode]’ for detailed documentation.
To see what version of ‘python-mode’ you are running,
enter ‘\\[py-version]’.

This mode knows about Python indentation,
tokens, comments (and continuation lines.
Paragraphs are separated by blank lines only.

COMMANDS

‘py-shell’	Start an interactive Python interpreter in another window
‘py-execute-statement’	Send statement at point to Python default interpreter
‘py-backward-statement’	Go to the initial line of a simple statement

etc.

See available commands listed in files commands-python-mode at directory doc

VARIABLES

‘py-indent-offset’ indentation increment
‘py-shell-name’ shell command to invoke Python interpreter
‘py-split-window-on-execute’ When non-nil split windowas
‘py-switch-buffers-on-execute-p’ When non-nil switch to the Python output buffer

\\{python-mode-map}

(fn)" t)
(autoload 'py-shell-mode "python-mode" "\
Major mode for Python shell process.

Variables
‘py-shell-prompt-regexp’,
‘py-shell-prompt-output-regexp’,
‘py-shell-input-prompt-2-regexp’,
‘py-shell-fontify-p’,
‘py-completion-setup-code’,
‘py-shell-completion-string-code’,
can customize this mode for different Python interpreters.

This mode resets ‘comint-output-filter-functions’ locally, so you
may want to re-add custom functions to it using the
‘py-shell-mode-hook’.

(Type \\[describe-mode] in the process buffer for a list of commands.)

(fn)" t)
(register-definition-prefixes "python-mode" '("all-mode-setting" "comint-mime-" "flake8" "force-py-shell-name-p-o" "gud-pdb-history" "highlight-indent-active" "hs-hide-comments-when-hiding-all" "info-lookup-mode" "ipython" "iypthon" "jython" "pdb-track-stack-from-shell-p" "pep8" "pst-here" "quote" "strip-chars-" "toggle-force-py-shell-name-p" "turn-o" "virtualenv-"))

;;; End of scraped data

(provide 'python-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; python-mode-autoloads.el ends here
