;;; terraform-doc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from terraform-doc.el

(autoload 'terraform-doc "terraform-doc" "\
Look up PROVIDER@VERSION.

(fn &optional PROVIDER VERSION)" t)
(register-definition-prefixes "terraform-doc" '("terraform-"))

;;; End of scraped data

(provide 'terraform-doc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; terraform-doc-autoloads.el ends here
