;;; mathjax-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mathjax.el

(autoload 'mathjax-shr-setup "mathjax" "\
Arrange for `shr' to use MathJax in this buffer.")
(register-definition-prefixes "mathjax" '("mathjax-"))

;;; End of scraped data

(provide 'mathjax-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mathjax-autoloads.el ends here
