;;; parse-it-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from parse-it.el

(autoload 'parse-it "parse-it" "\
Parse the PATH with symbol language LAN support.

If optional argument is nil; then it will use current buffer instead.

(fn LAN &optional PATH)")


;;; Generated autoloads from parse-it-actionscript.el

(register-definition-prefixes "parse-it-actionscript" '("parse-it-actionscript"))


;;; Generated autoloads from parse-it-asm.el

(register-definition-prefixes "parse-it-asm" '("parse-it-asm"))


;;; Generated autoloads from parse-it-ast.el

(register-definition-prefixes "parse-it-ast" '("parse-it-ast-"))


;;; Generated autoloads from parse-it-c.el

(register-definition-prefixes "parse-it-c" '("parse-it-c"))


;;; Generated autoloads from parse-it-c++.el

(register-definition-prefixes "parse-it-c++" '("parse-it-c++"))


;;; Generated autoloads from parse-it-csharp.el

(register-definition-prefixes "parse-it-csharp" '("parse-it-csharp"))


;;; Generated autoloads from parse-it-css.el

(register-definition-prefixes "parse-it-css" '("parse-it-css"))


;;; Generated autoloads from parse-it-elisp.el

(register-definition-prefixes "parse-it-elisp" '("parse-it-elisp"))


;;; Generated autoloads from parse-it-go.el

(register-definition-prefixes "parse-it-go" '("parse-it-go"))


;;; Generated autoloads from parse-it-html.el

(register-definition-prefixes "parse-it-html" '("parse-it-html"))


;;; Generated autoloads from parse-it-java.el

(register-definition-prefixes "parse-it-java" '("parse-it-java"))


;;; Generated autoloads from parse-it-js.el

(register-definition-prefixes "parse-it-js" '("parse-it-js"))


;;; Generated autoloads from parse-it-json.el

(register-definition-prefixes "parse-it-json" '("parse-it-json"))


;;; Generated autoloads from parse-it-kotlin.el

(register-definition-prefixes "parse-it-kotlin" '("parse-it-kotlin"))


;;; Generated autoloads from parse-it-lex.el

(register-definition-prefixes "parse-it-lex" '("parse-it-lex-"))


;;; Generated autoloads from parse-it-lisp.el

(register-definition-prefixes "parse-it-lisp" '("parse-it-lisp"))


;;; Generated autoloads from parse-it-lua.el

(register-definition-prefixes "parse-it-lua" '("parse-it-lua"))


;;; Generated autoloads from parse-it-markdown.el

(register-definition-prefixes "parse-it-markdown" '("parse-it-markdown"))


;;; Generated autoloads from parse-it-objc.el

(register-definition-prefixes "parse-it-objc" '("parse-it-objc"))


;;; Generated autoloads from parse-it-php.el

(register-definition-prefixes "parse-it-php" '("parse-it-php"))


;;; Generated autoloads from parse-it-python.el

(register-definition-prefixes "parse-it-python" '("parse-it-python"))


;;; Generated autoloads from parse-it-r.el

(register-definition-prefixes "parse-it-r" '("parse-it-r"))


;;; Generated autoloads from parse-it-sql.el

(register-definition-prefixes "parse-it-sql" '("parse-it-sql"))


;;; Generated autoloads from parse-it-swift.el

(register-definition-prefixes "parse-it-swift" '("parse-it-swift"))


;;; Generated autoloads from parse-it-typescript.el

(register-definition-prefixes "parse-it-typescript" '("parse-it-typescript"))


;;; Generated autoloads from parse-it-util.el

(register-definition-prefixes "parse-it-util" '("parse-it-util--"))


;;; Generated autoloads from parse-it-xml.el

(register-definition-prefixes "parse-it-xml" '("parse-it-xml"))

;;; End of scraped data

(provide 'parse-it-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; parse-it-autoloads.el ends here
