;;; el2markdown-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from el2markdown.el

(autoload 'el2markdown-view-buffer "el2markdown" "\
Convert comment section to markdown and display in temporary buffer." t)
(autoload 'el2markdown-write-file "el2markdown" "\
Convert comment section to markdown and write to file.

(fn &optional FILE-NAME OVERWRITE-WITHOUT-CONFIRM)" t)
(autoload 'el2markdown-write-readme "el2markdown" "\
Generate README.md, designed to be used in batch mode." t)
(register-definition-prefixes "el2markdown" '("el2markdown-"))

;;; End of scraped data

(provide 'el2markdown-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; el2markdown-autoloads.el ends here
