;;; bufferfile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bufferfile.el

(autoload 'bufferfile-rename "bufferfile" "\
Rename the file visited by the current buffer.
If BUFFER is provided, operate on the file visited by that buffer instead.

This command updates:
- The file name on disk,
- the buffer name,
- all the indirect buffers or other buffers associated with the old file.

Hooks in `bufferfile-pre-rename-functions' and
`bufferfile-post-rename-functions' are run before and after the renaming
process.

(fn &optional BUFFER)" t)
(autoload 'bufferfile-delete "bufferfile" "\
Kill the current buffer and delete the file associated with it.
Delete the file associated with a buffer and kill all buffers visiting the file,
including indirect buffers or clones.
If BUFFER is nil, operate on the current buffer.

Hooks in `bufferfile-pre-delete-functions' and
`bufferfile-post-delete-functions' are run before and after the renaming
process.

(fn &optional BUFFER)" t)
(register-definition-prefixes "bufferfile" '("bufferfile-"))

;;; End of scraped data

(provide 'bufferfile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bufferfile-autoloads.el ends here
