;;; ghub-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ghub.el

(autoload 'ghub-clear-caches "ghub" "\
Clear all caches that might negatively affect Ghub.

If a library that is used by Ghub caches incorrect information
such as a mistyped password, then that can prevent Ghub from
asking the user for the correct information again.

Set `url-http-real-basic-auth-storage' to nil
and call `auth-source-forget+'." t)
(register-definition-prefixes "ghub" '("auth-source-netrc-parse" "ghub-"))


;;; Generated autoloads from ghub-graphql.el

(register-definition-prefixes "ghub-graphql" '("ghub-"))


;;; Generated autoloads from ghub-legacy.el

(register-definition-prefixes "ghub-legacy" '("ghub-fetch-repository"))


;;; Generated autoloads from gsexp.el

(register-definition-prefixes "gsexp" '("gsexp-"))

;;; End of scraped data

(provide 'ghub-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ghub-autoloads.el ends here
