;;; tzc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tzc.el

(autoload 'tzc-convert-time "tzc" "\
Convert a given time as given in TIME-STRING from FROM-ZONE to TO-ZONE.
Optionally on a given FROM-DATE.

(fn TIME-STRING FROM-ZONE TO-ZONE &optional FROM-DATE)" t)
(autoload 'tzc-convert-current-time "tzc" "\
Convert current local time to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-convert-time-to-favourite-time-zones "tzc" "\
Convert time in TIME-STRING from FROM-ZONE to `(tzc--favourite-time-zones)`.
The conversion is computed for the given FROM-DATE.

(fn TIME-STRING FROM-ZONE FROM-DATE)" t)
(autoload 'tzc-convert-current-time-to-favourite-time-zones "tzc" "\
Convert current local time to `(tzc--favourite-time-zones)`." t)
(autoload 'tzc-add-or-update-time-zone-in-timestamp-at-point "tzc" "\
Add or update TIME-ZONE info for a timestamp at point.

(fn TIME-ZONE)" t)
(autoload 'tzc-convert-time-at-mark "tzc" "\
Convert time at point to TO-ZONE.

(fn TO-ZONE)" t)
(autoload 'tzc-world-clock-previous-or-next "tzc" "\
Get the `tzc-world-clock' buffer for PREVIOUS-OR-NEXT hour.

(fn PREVIOUS-OR-NEXT)")
(autoload 'tzc-world-clock-previous "tzc" "\
Get the `tzc-world-clock` for the previous hour." t)
(autoload 'tzc-world-clock-next "tzc" "\
Get the `tzc-world-clock` for the next hour." t)
(defvar tzc-world-clock-mode-map (let ((map (make-sparse-keymap))) (define-key map "n" #'tzc-world-clock-next) (define-key map "p" #'tzc-world-clock-previous) map))
(autoload 'tzc-world-clock "tzc" "\
Display a world clock buffer for time zones in `tzc-favourite-time-zones-alist`.
Optional argument FROM-TIME to convert time from.
Optional argument FROM-ZONE to convert time to.
Optional argument FROM-DATE to convert date from.

(fn &optional FROM-TIME FROM-ZONE FROM-DATE)" t)
(autoload 'tzc-check-time-zone "tzc" "\
Check info for TIME-ZONE.

(fn TIME-ZONE)" t)
(autoload 'tzc-convert-org-timestamp "tzc" "\
Convert TIMESTAMP to TO-ZONE.

(fn TIMESTAMP TO-ZONE)" t)
(autoload 'tzc-convert-org-timestamp-at-mark "tzc" "\
Convert `org-timestamp` at point to TO-ZONE.
Optional argument FROM-ZONE to use when not found at point.

(fn TO-ZONE &optional FROM-ZONE)" t)
(autoload 'tzc-convert-and-replace-org-timestamp-at-mark "tzc" "\
Convert `org-timestamp` at point to TO-ZONE and replace it.
Optional argument FROM-ZONE to use when not found at point.

(fn TO-ZONE &optional FROM-ZONE)" t)
(autoload 'tzc-get-time-shift-between-zones "tzc" "\
Get time shift between FROM-ZONE and TO-ZONE.
Optionally on a given FROM-DATE.

(fn FROM-ZONE TO-ZONE FROM-DATE)" t)
(register-definition-prefixes "tzc" '("tzc-"))


;;; Generated autoloads from tzc-org.el

(autoload 'tzc-org-schedule "tzc-org" "\
Schedule an org item with time zone conversion.
Similar to `org-schedule', but prompts for time zone conversion.
Prompts for date and time first, then asks for from-zone and to-zone,
converts the time, and inserts the result with the to-zone in the timestamp.
Optional argument ARG." t)
(autoload 'tzc-org-deadline "tzc-org" "\
Schedule an org item with time zone conversion.
Similar to `org-deadline', but prompts for time zone conversion.
Prompts for date and time first, then asks for from-zone and to-zone,
converts the time, and inserts the result with the to-zone in the timestamp.
Optional argument ARG." t)
(autoload 'tzc-org-mode "tzc-org" "\
Minor mode for TZC org features.

This is a minor mode.  If called interactively, toggle the `TZC-Org
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `tzc-org-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "tzc-org" '("tzc-"))

;;; End of scraped data

(provide 'tzc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tzc-autoloads.el ends here
