;;; speed-type-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from speed-type.el

(autoload 'speed-type-top-x "speed-type" "\
Speed type the N most common words.

(fn N)" t)
(autoload 'speed-type-top-100 "speed-type" "\
Speed type the top 100 most common words." t)
(autoload 'speed-type-top-1000 "speed-type" "\
Speed type the top 1000 most common words." t)
(autoload 'speed-type-region "speed-type" "\
Open copy of [START,END] in a new buffer to speed type the text.

(fn START END)" t)
(autoload 'speed-type-buffer "speed-type" "\
Open copy of buffer contents in a new buffer to speed type the text.

If using a prefix while calling this function `C-u', then the FULL text
will be used.  Else some text will be picked randomly.

(fn FULL)" t)
(autoload 'speed-type-text "speed-type" "\
Setup a new text sample to practice touch or speed typing." t)
(register-definition-prefixes "speed-type" '("speed-type-"))


;;; Generated autoloads from test-speed-type.el

(register-definition-prefixes "test-speed-type" '("speed-type--retrieve-"))

;;; End of scraped data

(provide 'speed-type-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; speed-type-autoloads.el ends here
