;;; elisp-depmap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elisp-depmap.el

(autoload 'elisp-depmap-makesummarytable "elisp-depmap" "\
Make a summary org table of variables and references to them." t)
(autoload 'elisp-depmap-graphviz-digraph "elisp-depmap" "\
Make a dot file representation of all definitions and references.
Optionally set INDENT-WIDTH which is 2 by default.
If SHUFFLE gives a random seed (default 0) to shuffle subgraph cluster layouts.

(fn &optional SHUFFLE)" t)
(autoload 'elisp-depmap-graphviz "elisp-depmap" "\
Make basic dot file of top level definitions and their references." t)


;;; Generated autoloads from elisp-depmap-exec.el

(register-definition-prefixes "elisp-depmap-exec" '("elisp-depmap-exec-"))


;;; Generated autoloads from elisp-depmap-graph.el

(register-definition-prefixes "elisp-depmap-graph" '("elisp-depmap-graph-"))


;;; Generated autoloads from elisp-depmap-parse.el

(register-definition-prefixes "elisp-depmap-parse" '("elisp-depmap-parse-"))


;;; Generated autoloads from elisp-depmap-secondhelp.el

(register-definition-prefixes "elisp-depmap-secondhelp" '("elisp-depmap-secondhelp-"))

;;; End of scraped data

(provide 'elisp-depmap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elisp-depmap-autoloads.el ends here
