;;; eros-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eros.el

(autoload 'eros-eval-overlay "eros" "\
Make overlay for STRING value at POINT.

(fn STRING POINT)")
(autoload 'eros-eval-last-sexp "eros" "\
Wrapper for `eval-last-sexp' that overlays results.

(fn EVAL-LAST-SEXP-ARG-INTERNAL)" t)
(autoload 'eros-eval-defun "eros" "\
Wrapper for `eval-defun' that overlays results.

(fn EDEBUG-IT)" t)
(defvar eros-mode nil "\
Non-nil if Eros mode is enabled.
See the `eros-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `eros-mode'.")
(custom-autoload 'eros-mode "eros" nil)
(autoload 'eros-mode "eros" "\
Display Emacs Lisp evaluation results overlays.

This is a global minor mode.  If called interactively, toggle the `Eros
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='eros-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "eros" '("eros-"))

;;; End of scraped data

(provide 'eros-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eros-autoloads.el ends here
