;;; term-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from term-projectile.el

(autoload 'term-projectile-switch-to "term-projectile" "\
Switch to an existing term-projectile buffer using `completing-read'." t)
(autoload 'term-projectile-forward "term-projectile" "\
Switch forward to the next term-projectile ansi-term buffer.
Make a new one if none exists." t)
(autoload 'term-projectile-backward "term-projectile" "\
Switch backward to the next term-projectile ansi-term buffer.
Make a new one if none exists." t)
(autoload 'term-projectile-create-new "term-projectile" "\
Make a new `ansi-term' buffer for DIRECTORY.
If directory is nil, use the current projectile project

(fn &optional (DIRECTORY (projectile-project-root)))" t)
(autoload 'term-projectile-default-directory-forward "term-projectile" "\
Switch forward to the next term-projectile ansi-term buffer for `default-directory'." t)
(autoload 'term-projectile-default-directory-backward "term-projectile" "\
Switch backward to the next term-projectile ansi-term buffer for `default-directory'." t)
(autoload 'term-projectile-default-directory-create-new "term-projectile" "\
Make a new `ansi-term' buffer in `default-directory'." t)
(autoload 'term-projectile-global-forward "term-projectile" "\
Switch forward to the next term-projectile ansi-term buffer.
Make a new one if none exists." t)
(autoload 'term-projectile-global-backward "term-projectile" "\
Switch backward to the next term-projectile ansi-term buffer.
Make a new one if none exists." t)
(autoload 'term-projectile-global-create-new "term-projectile" "\
Make a new `ansi-term' buffer in `term-projectile-global-directory'." t)
(register-definition-prefixes "term-projectile" '("maybe-intern" "term-projectile"))

;;; End of scraped data

(provide 'term-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; term-projectile-autoloads.el ends here
