;;; flymake-phpstan-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-phpstan.el

(autoload 'flymake-phpstan-turn-on "flymake-phpstan" "\
Enable `flymake-phpstan' as buffer-local Flymake backend." t)
(register-definition-prefixes "flymake-phpstan" '("flymake-phpstan"))

;;; End of scraped data

(provide 'flymake-phpstan-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-phpstan-autoloads.el ends here
