;;; reveal-in-folder-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from reveal-in-folder.el

(autoload 'reveal-in-folder-open "reveal-in-folder" "\
Reveal folder in PATH.

(fn PATH)")
(autoload 'reveal-in-folder-at-point "reveal-in-folder" "\
Reveal the current file in folder at point." t)
(autoload 'reveal-in-folder-this-buffer "reveal-in-folder" "\
Reveal the current buffer in folder." t)
(autoload 'reveal-in-folder "reveal-in-folder" "\
Reveal buffer/path depends on cursor condition." t)
(register-definition-prefixes "reveal-in-folder" '("reveal-in-folder-"))

;;; End of scraped data

(provide 'reveal-in-folder-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; reveal-in-folder-autoloads.el ends here
