;;; shfmt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shfmt.el

 (autoload 'shfmt-buffer "shfmt" nil t)
 (autoload 'shfmt-region "shfmt" nil t)
 (autoload 'shfmt-on-save-mode "shfmt" nil t)
(register-definition-prefixes "shfmt" '("shfmt-"))

;;; End of scraped data

(provide 'shfmt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shfmt-autoloads.el ends here
