;;; rfc-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rfc-mode.el

(autoload 'rfc-mode-read "rfc-mode" "\
Read the RFC document NUMBER.
Offer the number at point as default.

(fn NUMBER)" t)
(autoload 'rfc-mode-browse "rfc-mode" "\
Browse through all RFC documents referenced in the index." t)
(autoload 'rfc-mode "rfc-mode" "\
Major mode to browse and read RFC documents.

(fn)" t)
(add-to-list 'auto-mode-alist '("/rfc[0-9]+\\.txt\\'" . rfc-mode))
(register-definition-prefixes "rfc-mode" '("rfc-mode-"))

;;; End of scraped data

(provide 'rfc-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rfc-mode-autoloads.el ends here
