;;; nix-update-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nix-update.el

(autoload 'nix-update-fetch "nix-update" "\
Update the nix fetch expression at point.
If ARG is non-nil, fully update the expression and not just the SHA.
With two prefix arguments, update all expressions in the buffer.

(fn &optional ARG)" t)
(register-definition-prefixes "nix-update" '("nix-update-"))

;;; End of scraped data

(provide 'nix-update-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nix-update-autoloads.el ends here
