;;; async-backup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from async-backup.el

(autoload 'async-backup "async-backup" "\
Backup FILE, or file visited by current buffer.

(fn &optional FILE)")
(register-definition-prefixes "async-backup" '("async-backup-"))

;;; End of scraped data

(provide 'async-backup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; async-backup-autoloads.el ends here
