;;; buffer-guardian-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from buffer-guardian.el

(autoload 'buffer-guardian-save-buffer-maybe "buffer-guardian" "\
Save BUFFER if it is visiting a file that is existing on the disk.
By default, it only saves when the file exists on the disk.

(fn &optional BUFFER)")
(autoload 'buffer-guardian-save-all-buffers "buffer-guardian" "\
Save all modified buffers that are visiting files that exist on the disk.
BUFFER-LIST is the list of buffers.

(fn &optional BUFFER-LIST)")
(defvar buffer-guardian-mode nil "\
Non-nil if Buffer-Guardian mode is enabled.
See the `buffer-guardian-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `buffer-guardian-mode'.")
(custom-autoload 'buffer-guardian-mode "buffer-guardian" nil)
(autoload 'buffer-guardian-mode "buffer-guardian" "\
Toggle `buffer-guardian-mode'.

This is a global minor mode.  If called interactively, toggle the
`Buffer-Guardian mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='buffer-guardian-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "buffer-guardian" '("buffer-guardian-"))

;;; End of scraped data

(provide 'buffer-guardian-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; buffer-guardian-autoloads.el ends here
