;;; inline-docs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from inline-docs.el

(autoload 'inline-docs-display-docs-momentary "inline-docs" "\
Display inline docs FORMAT-STRING under point with extra ARGS.

(fn FORMAT-STRING &rest ARGS)")
(defalias 'inline-docs 'inline-docs-display-docs-momentary)
(register-definition-prefixes "inline-docs" '("inline-docs-"))

;;; End of scraped data

(provide 'inline-docs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; inline-docs-autoloads.el ends here
