;;; lsp-ivy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lsp-ivy.el

(autoload 'lsp-ivy-workspace-symbol "lsp-ivy" "\
`ivy' for lsp workspace/symbol.
When called with prefix ARG the default selection will be symbol at point.

(fn ARG)" t)
(autoload 'lsp-ivy-global-workspace-symbol "lsp-ivy" "\
`ivy' for lsp workspace/symbol for all of the current workspaces.
When called with prefix ARG the default selection will be symbol at point.

(fn ARG)" t)
(autoload 'lsp-ivy-workspace-folders-remove "lsp-ivy" "\
Remove a project-root from the list of workspace folders." t)
(register-definition-prefixes "lsp-ivy" '("lsp-ivy-"))

;;; End of scraped data

(provide 'lsp-ivy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-ivy-autoloads.el ends here
