;;; free-keys-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from free-keys.el

(autoload 'free-keys "free-keys" "\
Display free keys in current buffer.

A free key is a key that has no associated key binding as
determined by function `key-binding' .

By default, keys on `free-keys-keys' list with no prefix sequence
are considered, possibly together with modifier keys from
`free-keys-modifiers'.  You can change the prefix sequence by
hitting p in the *Free keys* buffer.  PREFIX is supplied in
format recognized by `kbd', for example `C-x'.

By default, the list is shown for the current buffer,
unless BUFFER specifies another one.

(fn &optional PREFIX BUFFER)" t)
(register-definition-prefixes "free-keys" '("free-keys-"))

;;; End of scraped data

(provide 'free-keys-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; free-keys-autoloads.el ends here
