;;; tree-inspector-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tree-inspector.el

(autoload 'tree-inspector-inspect-last-sexp "tree-inspector" "\
Evaluate sexp before point and inspect the result." t)
(autoload 'tree-inspector-inspect-defun "tree-inspector" "\
Inspect the top-level defun." t)
(autoload 'tree-inspector-inspect-region "tree-inspector" "\
Inspect the region.

(fn START END)" t)
(autoload 'tree-inspector-inspect-expression "tree-inspector" "\
Evaluate EXP and inspect its result with a tree-inspector.

(fn EXP)" t)
(register-definition-prefixes "tree-inspector" '("tree-inspector-"))


;;; Generated autoloads from tree-inspector-tests.el

(register-definition-prefixes "tree-inspector-tests" '("inspector-tests--person" "tree-inspector-tests-"))

;;; End of scraped data

(provide 'tree-inspector-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tree-inspector-autoloads.el ends here
