;;; separedit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from separedit.el

(autoload 'separedit-dwim-described-variable "separedit" "\
Edit value of variable at poin in help/helpful buffer." t)
(autoload 'separedit-dwim-vterm "separedit" "\
Edit content after vterm prompt." t)
(autoload 'separedit-dwim-default "separedit" "\
Edit comment or docstring or code BLOCK in them.

Normally, the major mode of the edit buffer will be selected automatically,
but users can also manually select it by pressing `C-u \\[separedit]'.

(fn &optional BLOCK)" t)
(autoload 'separedit-dwim "separedit" "\


(fn &optional BLOCK)" t)
(defalias 'separedit 'separedit-dwim)
(register-definition-prefixes "separedit" '("separedit-"))

;;; End of scraped data

(provide 'separedit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; separedit-autoloads.el ends here
